# Generated by Django 3.2.5 on 2021-08-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
